count_find: count_find.cpp
	g++ -std=c++11 -o $@ $^

search: search.cpp
	g++ -std=c++11 -o $@ $^

max_min_val: max_min_val.cpp
	g++ -std=c++11 -o $@ $^

accumulate: accumulate.cpp
	g++ -std=c++11 -o $@ $^

fill: fill.cpp
	g++ -std=c++11 -o $@ $^

clean:
	sudo rm -rf count_find
	sudo rm -rf search 
	sudo rm -rf max_min_val 
	sudo rm -rf accumulate
	sudo rm -rf fill
