count_find: count_find.cpp
	g++ -std=c++11 -o $@ $^

search: search.cpp
	g++ -std=c++11 -o $@ $^

max_min_val: max_min_val.cpp
	g++ -std=c++11 -o $@ $^

accumulate: accumulate.cpp
	g++ -std=c++11 -o $@ $^

fill: fill.cpp
	g++ -std=c++11 -o $@ $^

search_1: search_1.cpp
	g++ -std=c++11 -o $@ $^

find_first_of: find_first_of.cpp
	g++ -std=c++11 -o $@ $^

adjacent: adjacent.cpp
	g++ -std=c++11 -o $@ $^

binary_search: binary_search.cpp
	g++ -std=c++11 -o $@ $^

include: include.cpp
	g++ -std=c++11 -o $@ $^

clean:
	sudo rm -rf count_find
	sudo rm -rf search 
	sudo rm -rf max_min_val 
	sudo rm -rf accumulate
	sudo rm -rf fill
	sudo rm -rf search_1
	sudo rm -rf find_first_of
	sudo rm -rf binary_search
	sudo rm -rf adjacent
	sudo rm -rf include
