vector:vector.cpp
	g++ -Wall -g -std=c++11 -o $@ $^

invaliditerator: invaliditerator.cpp
	g++ -Wall -g -std=c++11 -o $@ $^

forward_list: forward_list.cpp
	g++ -Wall -g -std=c++11 -o $@ $^

algorithmconcept: algorithmconcept.cpp
	g++ -std=c++11 -o $@ $^

string: stringcontainter.cpp
	g++ -std=c++11 -o $@ $^

deque: deque.cpp
	g++ -std=c++11 -o $@ $^

set: set_multisets_hashset.cpp
	g++ -std=c++11 -o $@ $^

map: map_multimap_hashmap.cpp
	g++ -std=c++11 -o $@ $^

stack: stack.cpp
	g++ -std=c++11 -o $@ $^

queue: queue.cpp
	g++ -std=c++11 -o $@ $^

priority_queue: priority_queue.cpp
	g++ -std=c++11 -o $@ $^

funcobject: functionobject.cpp
	g++ -std=c++11 -o $@ $^

clean:
	sudo rm -rf string
	sudo rm -rf app
	sudo rm -rf vector
	sudo rm -rf deque
	sudo rm -rf set 
	sudo rm -rf map 
	sudo rm -rf stack	
	sudo rm -rf queue
	sudo rm -rf priority_queue
	sudo rm -rf functionobject
