app:vector.cpp
	g++ -Wall -g -std=c++11 -o $@ $^

invaliditerator: invaliditerator.cpp
	g++ -Wall -g -std=c++11 -o $@ $^

forward_list: forward_list.cpp
	g++ -Wall -g -std=c++11 -o $@ $^

vector: vector.cpp
	g++ -Wall -g -std=c++11 -o $@ $^
app.out: algorithmconcept.cpp
	g++ -std=c++11 -o $@ $^
stringcontainer.out: stringcontainter.cpp
	g++ -std=c++11 -o $@ $^

clean:
	sudo rm -rf stringcontainer.out
